### Finetuning for Text Classification

In [5]:
import sys
!{sys.executable} -m pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
     ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
     ---------------------------------------- 0.1/11.3 MB 3.3 MB/s eta 0:00:04
      --------------------------------------- 0.2/11.3 MB 2.1 MB/s eta 0:00:06
     - -------------------------------------- 0.3/11.3 MB 2.3 MB/s eta 0:00:05
     - -------------------------------------- 0.5/11.3 MB 2.6 MB/s eta 0:00:05
     -- ------------------------------------- 0.6/11.3 MB 2.9 MB/s eta 0:00:04
     -- ------------------------------------- 0.7/11.3 MB 2.7 MB/s eta 0:00:04
     -- ------------------------------------- 0.8/11.3 MB 2.6 MB/s eta 0:00:04
     --- ------------------------------------ 0.9/11.3 MB 2.6 MB/s eta 0:00:04
     --- ------------------------------------ 1.1/11.3 MB 2.6 MB/s eta 0:00:04
     ---- ----------------------------------- 1.3/11.3 MB 2.7 MB/s eta 0:00:04
     ---- ----------------------------------- 1.4/11.3 MB 2.8 MB/s eta 0:00:04
     ----- ---------------------------------- 1.6/11.3 MB 2.8 MB/s eta 0:00:04
     ----- ---------------------------------- 1.6/11.3 MB 2.8 MB/s eta 0:00:04
     ----- ---------------------------------- 1.7/11.3 MB 2.6 MB/s eta 0:00:04
     ----- ---------------------------------- 1.7/11.3 MB 2.6 MB/s eta 0:00:04
     ----- ---------------------------------- 1.7/11.3 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.8/11.3 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.9/11.3 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.9/11.3 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.9/11.3 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.9/11.3 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.9/11.3 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.9/11.3 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.9/11.3 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.9/11.3 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.9/11.3 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.9/11.3 MB 2.3 MB/s eta 0:00:05
     ------- -------------------------------- 2.0/11.3 MB 1.6 MB/s eta 0:00:06
     ------- -------------------------------- 2.1/11.3 MB 1.6 MB/s eta 0:00:06
     ------- -------------------------------- 2.2/11.3 MB 1.6 MB/s eta 0:00:06
     -------- ------------------------------- 2.4/11.3 MB 1.6 MB/s eta 0:00:06
     -------- ------------------------------- 2.5/11.3 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 2.7/11.3 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 2.8/11.3 MB 1.7 MB/s eta 0:00:05
     ---------- ----------------------------- 2.9/11.3 MB 1.8 MB/s eta 0:00:05
     ---------- ----------------------------- 3.0/11.3 MB 1.8 MB/s eta 0:00:05
     ---------- ----------------------------- 3.1/11.3 MB 1.8 MB/s eta 0:00:05
     ----------- ---------------------------- 3.1/11.3 MB 1.8 MB/s eta 0:00:05
     ----------- ---------------------------- 3.2/11.3 MB 1.8 MB/s eta 0:00:05
     ----------- ---------------------------- 3.3/11.3 MB 1.8 MB/s eta 0:00:05
     ----------- ---------------------------- 3.3/11.3 MB 1.8 MB/s eta 0:00:05
     ------------ --------------------------- 3.4/11.3 MB 1.8 MB/s eta 0:00:05
     ------------ --------------------------- 3.5/11.3 MB 1.7 MB/s eta 0:00:05
     ------------ --------------------------- 3.5/11.3 MB 1.7 MB/s eta 0:00:05
     ------------ --------------------------- 3.5/11.3 MB 1.7 MB/s eta 0:00:05
     ------------ --------------------------- 3.6/11.3 MB 1.7 MB/s eta 0:00:05
     ------------ --------------------------- 3.6/11.3 MB 1.7 MB/s eta 0:00:05
     ------------- -------------------------- 3.7/11.3 MB 1.7 MB/s eta 0:00:05
     ------------- -------------------------- 3.8/11.3 MB 1.7 MB/s eta 0:00:05
     ------------- -------------------------- 3.9/11.3 MB 1.7 MB/s eta 0:00:05
     ------------- -------------------------- 4.0/11.3 MB 1.7 MB/s eta 0:00:05
     -------------- ------------------------- 4.1/11.3 MB 1.7 MB/s eta 0:00:05
     -------------- ------------------------- 4.2/11.3 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 4.3/11.3 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 4.4/11.3 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 4.5/11.3 MB 1.7 MB/s eta 0:00:05
     ---------------- ----------------------- 4.6/11.3 MB 1.7 MB/s eta 0:00:04
     ---------------- ----------------------- 4.7/11.3 MB 1.7 MB/s eta 0:00:04
     ---------------- ----------------------- 4.7/11.3 MB 1.7 MB/s eta 0:00:04
     ---------------- ----------------------- 4.7/11.3 MB 1.7 MB/s eta 0:00:04
     ---------------- ----------------------- 4.8/11.3 MB 1.7 MB/s eta 0:00:04
     ----------------- ---------------------- 4.9/11.3 MB 1.7 MB/s eta 0:00:04
     ----------------- ---------------------- 4.9/11.3 MB 1.7 MB/s eta 0:00:04
     ----------------- ---------------------- 5.0/11.3 MB 1.7 MB/s eta 0:00:04
     ------------------ --------------------- 5.2/11.3 MB 1.7 MB/s eta 0:00:04
     ------------------ --------------------- 5.3/11.3 MB 1.7 MB/s eta 0:00:04
     ------------------ --------------------- 5.3/11.3 MB 1.7 MB/s eta 0:00:04
     ------------------- -------------------- 5.5/11.3 MB 1.7 MB/s eta 0:00:04
     ------------------- -------------------- 5.6/11.3 MB 1.7 MB/s eta 0:00:04
     -------------------- ------------------- 5.8/11.3 MB 1.8 MB/s eta 0:00:04
     -------------------- ------------------- 5.9/11.3 MB 1.8 MB/s eta 0:00:04
     --------------------- ------------------ 6.0/11.3 MB 1.8 MB/s eta 0:00:03
     --------------------- ------------------ 6.2/11.3 MB 1.8 MB/s eta 0:00:03
     ---------------------- ----------------- 6.3/11.3 MB 1.8 MB/s eta 0:00:03
     ---------------------- ----------------- 6.5/11.3 MB 1.9 MB/s eta 0:00:03
     ----------------------- ---------------- 6.6/11.3 MB 1.9 MB/s eta 0:00:03
     ----------------------- ---------------- 6.7/11.3 MB 1.9 MB/s eta 0:00:03
     ------------------------ --------------- 6.8/11.3 MB 1.9 MB/s eta 0:00:03
     ------------------------ --------------- 6.9/11.3 MB 1.9 MB/s eta 0:00:03
     ------------------------ --------------- 6.9/11.3 MB 1.9 MB/s eta 0:00:03
     ------------------------ --------------- 7.0/11.3 MB 1.9 MB/s eta 0:00:03
     ------------------------- -------------- 7.2/11.3 MB 1.9 MB/s eta 0:00:03
     ------------------------- -------------- 7.2/11.3 MB 1.9 MB/s eta 0:00:03
     -------------------------- ------------- 7.4/11.3 MB 1.9 MB/s eta 0:00:03
     -------------------------- ------------- 7.5/11.3 MB 1.9 MB/s eta 0:00:03
     --------------------------- ------------ 7.7/11.3 MB 1.9 MB/s eta 0:00:02
     --------------------------- ------------ 7.8/11.3 MB 1.9 MB/s eta 0:00:02
     ---------------------------- ----------- 8.0/11.3 MB 2.0 MB/s eta 0:00:02
     ---------------------------- ----------- 8.2/11.3 MB 2.0 MB/s eta 0:00:02
     ----------------------------- ---------- 8.3/11.3 MB 2.0 MB/s eta 0:00:02
     ----------------------------- ---------- 8.5/11.3 MB 2.0 MB/s eta 0:00:02
     ------------------------------ --------- 8.7/11.3 MB 2.0 MB/s eta 0:00:02
     ------------------------------- -------- 8.8/11.3 MB 2.0 MB/s eta 0:00:02
     ------------------------------- -------- 9.0/11.3 MB 2.1 MB/s eta 0:00:02
     -------------------------------- ------- 9.2/11.3 MB 2.1 MB/s eta 0:00:02
     -------------------------------- ------- 9.3/11.3 MB 2.1 MB/s eta 0:00:01
     --------------------------------- ------ 9.5/11.3 MB 2.1 MB/s eta 0:00:01
     --------------------------------- ------ 9.6/11.3 MB 2.1 MB/s eta 0:00:01
     --------------------------------- ------ 9.6/11.3 MB 2.1 MB/s eta 0:00:01
     ---------------------------------- ----- 9.7/11.3 MB 2.1 MB/s eta 0:00:01
     ---------------------------------- ----- 9.8/11.3 MB 2.1 MB/s eta 0:00:01
     ----------------------------------- ---- 10.0/11.3 MB 2.1 MB/s eta 0:00:01
     ----------------------------------- ---- 10.1/11.3 MB 2.1 MB/s eta 0:00:01
     ----------------------------------- ---- 10.1/11.3 MB 2.1 MB/s eta 0:00:01
     ------------------------------------ --- 10.2/11.3 MB 2.1 MB/s eta 0:00:01
     ------------------------------------ --- 10.4/11.3 MB 2.1 MB/s eta 0:00:01
     ------------------------------------- -- 10.5/11.3 MB 2.1 MB/s eta 0:00:01
     ------------------------------------- -- 10.6/11.3 MB 2.1 MB/s eta 0:00:01
     ------------------------------------- -- 10.7/11.3 MB 2.1 MB/s eta 0:00:01
     -------------------------------------- - 10.8/11.3 MB 2.1 MB/s eta 0:00:01
     -------------------------------------- - 11.0/11.3 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------  11.1/11.3 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------  11.2/11.3 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------  11.2/11.3 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------  11.3/11.3 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------  11.3/11.3 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------  11.3/11.3 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------  11.3/11.3 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------- 11.3/11.3 MB 2.0 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
     ---------------------------------------- 0.0/509.2 kB ? eta -:--:--
     ---- ---------------------------------- 61.4/509.2 kB 1.7 MB/s eta 0:00:01
     --------- ---------------------------- 122.9/509.2 kB 1.4 MB/s eta 0:00:01
     --------------- ---------------------- 204.8/509.2 kB 1.6 MB/s eta 0:00:01
     ---------------------- --------------- 307.2/509.2 kB 1.7 MB/s eta 0:00:01
     ----------------------------- -------- 389.1/509.2 kB 1.7 MB/s eta 0:00:01
     --------------------------------- ---- 450.6/509.2 kB 1.7 MB/s eta 0:00:01
     -------------------------------------  501.8/509.2 kB 1.7 MB/s eta 0:00:01
     -------------------------------------- 509.2/509.2 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in d:\llms-from-scratch\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in d:\llms-from-scratch\.venv\lib\site-packages (from pandas) (2.2.6)
Collecting tzdata>=2022.7
  Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
     ---------------------------------------- 0.0/348.5 kB ? eta -:--:--
     -------- ------------------------------ 71.7/348.5 kB 2.0 MB/s eta 0:00:01
     ------------------ ------------------- 174.1/348.5 kB 1.8 MB/s eta 0:00:01
     ------------------------- ------------ 235.5/348.5 kB 1.6 MB/s eta 0:00:01
     --------------------------------- ---- 307.2/348.5 kB 1.6 MB/s eta 0:00:01
     -------------------------------------- 348.5/348.5 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in d:\llms-from-scratch\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.3.3 pytz-2025.2 tzdata-2025.3

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
from importlib.metadata import version

pkgs = ["matplotlib",  # Plotting library
        "numpy",       # PyTorch & TensorFlow dependency
        "tiktoken",    # Tokenizer
        "torch",       # Deep learning library
        "tensorflow",  # For OpenAI's pretrained weights
        "pandas"       # Dataset loading
       ]
for p in pkgs:
    print(f"{p} version: {version(p)}")

matplotlib version: 3.10.8
numpy version: 2.2.6
tiktoken version: 0.12.0
torch version: 2.10.0
tensorflow version: 2.20.0
pandas version: 2.3.3

### Different categories of finetuning

* This section prepares the dataset we use for classification finetuning
* We use a dataset consisting of spam and non-spam text messages to finetune the LLM to classify them
* First, we download and unzip the dataset

In [7]:
import requests
import zipfile
import os
from pathlib import Path

url = "https://archive.ics.uci.edu/static/public/228/sms+spam+collection.zip"
zip_path = "sms_spam_collection.zip"
extracted_path = "sms_spam_collection"
data_file_path = Path(extracted_path) / "SMSSpamCollection.tsv"


def download_and_unzip_spam_data(url, zip_path, extracted_path, data_file_path):
    if data_file_path.exists():
        print(f"{data_file_path} already exists. Skipping download and extraction.")
        return

    # Downloading the file
    response = requests.get(url, stream=True, timeout=60)
    response.raise_for_status()
    with open(zip_path, "wb") as out_file:
        for chunk in response.iter_content(chunk_size=8192):
            if chunk:
                out_file.write(chunk)

    # Unzipping the file
    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(extracted_path)

    # Add .tsv file extension
    original_file_path = Path(extracted_path) / "SMSSpamCollection"
    os.rename(original_file_path, data_file_path)
    print(f"File downloaded and saved as {data_file_path}")


try:
    download_and_unzip_spam_data(url, zip_path, extracted_path, data_file_path)
except (requests.exceptions.RequestException, TimeoutError) as e:
    print(f"Primary URL failed: {e}. Trying backup URL...")
    url = "https://f001.backblazeb2.com/file/LLMs-from-scratch/sms%2Bspam%2Bcollection.zip"
    download_and_unzip_spam_data(url, zip_path, extracted_path, data_file_path)

File downloaded and saved as sms_spam_collection\SMSSpamCollection.tsv

* The dataset is saved as a tab-separated text file, which we can load into a pandas DataFrame

In [8]:
import pandas as pd

df = pd.read_csv(data_file_path, sep="\t", header=None, names=["Label", "Text"])
df

     Label                                               Text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

* When we check the class distribution, we see that the data contains "ham" (i.e., "not spam") much more frequently than "spam"

In [9]:
print(df["Label"].value_counts())

Label
ham     4825
spam     747
Name: count, dtype: int64

For simplicity, and because we prefer a small dataset for educational purposes anyway (it will make it possible to finetune the LLM faster), we subsample (undersample) the dataset so that it contains 747 instances from each class
(Next to undersampling, there are several other ways to deal with class balances, but they are out of the scope of a book on LLMs;

In [10]:
def create_balanced_dataset(df):
    
    # Count the instances of "spam"
    num_spam = df[df["Label"] == "spam"].shape[0]
    
    # Randomly sample "ham" instances to match the number of "spam" instances
    ham_subset = df[df["Label"] == "ham"].sample(num_spam, random_state=123)
    
    # Combine ham "subset" with "spam"
    balanced_df = pd.concat([ham_subset, df[df["Label"] == "spam"]])

    return balanced_df


balanced_df = create_balanced_dataset(df)
print(balanced_df["Label"].value_counts())

Label
ham     747
spam    747
Name: count, dtype: int64

* Next, we change the string class labels "ham" and "spam" into integer class labels 0 and 1:

In [11]:
balanced_df["Label"] = balanced_df["Label"].map({"ham": 0, "spam": 1})

In [12]:
balanced_df

      Label                                               Text
4307      0  Awww dat is sweet! We can think of something t...
4138      0                             Just got to  &lt;#&gt;
4831      0  The word "Checkmate" in chess comes from the P...
4461      0  This is wishing you a great day. Moji told me ...
5440      0      Thank you. do you generally date the brothas?
...     ...                                                ...
5537      1  Want explicit SEX in 30 secs? Ring 02073162414...
5540      1  ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...
5547      1  Had your contract mobile 11 Mnths? Latest Moto...
5566      1  REMINDER FROM O2: To get 2.50 pounds free call...
5567      1  This is the 2nd time we have tried 2 contact u...

[1494 rows x 2 columns]

* Let's now define a function that randomly divides the dataset into training, validation, and test subsets

In [13]:
def random_split(df, train_frac, validation_frac):
    # Shuffle the entire DataFrame
    df = df.sample(frac=1, random_state=123).reset_index(drop=True)

    # Calculate split indices
    train_end = int(len(df) * train_frac)
    validation_end = train_end + int(len(df) * validation_frac)

    # Split the DataFrame
    train_df = df[:train_end]
    validation_df = df[train_end:validation_end]
    test_df = df[validation_end:]

    return train_df, validation_df, test_df

train_df, validation_df, test_df = random_split(balanced_df, 0.7, 0.1)
# Test size is implied to be 0.2 as the remainder

train_df.to_csv("train.csv", index=None)
validation_df.to_csv("validation.csv", index=None)
test_df.to_csv("test.csv", index=None)

### Creating data loaders

Note that the text messages have different lengths; if we want to combine multiple training examples in a batch, we have to either

truncate all messages to the length of the shortest message in the dataset or batch
pad all messages to the length of the longest message in the dataset or batch
We choose option 2 and pad all messages to the longest message in the dataset

For that, we use <|endoftext|> as a padding token, as discussed in chapter 2

In [14]:
import tiktoken

tokenizer = tiktoken.get_encoding("gpt2")
print(tokenizer.encode("<|endoftext|>", allowed_special={"<|endoftext|>"}))

[50256]

The SpamDataset class below identifies the longest sequence in the training dataset and adds the padding token to the others to match that sequence length

In [15]:
import torch
from torch.utils.data import Dataset


class SpamDataset(Dataset):
    def __init__(self, csv_file, tokenizer, max_length=None, pad_token_id=50256):
        self.data = pd.read_csv(csv_file)

        # Pre-tokenize texts
        self.encoded_texts = [
            tokenizer.encode(text) for text in self.data["Text"]
        ]

        if max_length is None:
            self.max_length = self._longest_encoded_length()
        else:
            self.max_length = max_length
            # Truncate sequences if they are longer than max_length
            self.encoded_texts = [
                encoded_text[:self.max_length]
                for encoded_text in self.encoded_texts
            ]

        # Pad sequences to the longest sequence
        self.encoded_texts = [
            encoded_text + [pad_token_id] * (self.max_length - len(encoded_text))
            for encoded_text in self.encoded_texts
        ]

    def __getitem__(self, index):
        encoded = self.encoded_texts[index]
        label = self.data.iloc[index]["Label"]
        return (
            torch.tensor(encoded, dtype=torch.long),
            torch.tensor(label, dtype=torch.long)
        )

    def __len__(self):
        return len(self.data)

    def _longest_encoded_length(self):
        max_length = 0
        for encoded_text in self.encoded_texts:
            encoded_length = len(encoded_text)
            if encoded_length > max_length:
                max_length = encoded_length
        return max_length

In [16]:
train_dataset = SpamDataset(
    csv_file="train.csv",
    max_length=None,
    tokenizer=tokenizer
)

print(train_dataset.max_length)

120

We also pad the validation and test set to the longest training sequence
Note that validation and test set samples that are longer than the longest training example are being truncated via encoded_text[:self.max_length] in the SpamDataset code
This behavior is entirely optional, and it would also work well if we set max_length=None in both the validation and test set cases

In [17]:
val_dataset = SpamDataset(
    csv_file="validation.csv",
    max_length=train_dataset.max_length,
    tokenizer=tokenizer
)
test_dataset = SpamDataset(
    csv_file="test.csv",
    max_length=train_dataset.max_length,
    tokenizer=tokenizer
)

Next, we use the dataset to instantiate the data loaders, which is similar to creating the data loaders in previous chapters

In [18]:
from torch.utils.data import DataLoader

num_workers = 0
batch_size = 8

torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_dataset,
    batch_size=batch_size,
    shuffle=True,
    num_workers=num_workers,
    drop_last=True,
)

val_loader = DataLoader(
    dataset=val_dataset,
    batch_size=batch_size,
    num_workers=num_workers,
    drop_last=False,
)

test_loader = DataLoader(
    dataset=test_dataset,
    batch_size=batch_size,
    num_workers=num_workers,
    drop_last=False,
)

As a verification step, we iterate through the data loaders and ensure that the batches contain 8 training examples each, where each training example consists of 120 tokens

In [19]:
print("Train loader:")
for input_batch, target_batch in train_loader:
    pass

print("Input batch dimensions:", input_batch.shape)
print("Label batch dimensions", target_batch.shape)

Train loader:
Input batch dimensions: torch.Size([8, 120])
Label batch dimensions torch.Size([8])

Lastly, let's print the total number of batches in each dataset

In [20]:
print(f"{len(train_loader)} training batches")
print(f"{len(val_loader)} validation batches")
print(f"{len(test_loader)} test batches")

130 training batches
19 validation batches
38 test batches